/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2projelogintasarim;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class Admin_Emplooyes_Management extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Emplooyes_Management
     */
    DefaultTableModel tbl_table_model;
    DefaultTableModel tbl_table_model_candidates;
    Candidate cndts;

    public Admin_Emplooyes_Management() {
        initComponents();
        tbl_table_model = new DefaultTableModel();
        tbl_table_model.setColumnIdentifiers(new Object[]{"ID", "NAME", "EMAIL", "PASSWORD", "ADDRESS", "GENDER", "POSITION", "SALARY"});
        tbl_admin_emplooyes_management.setModel(tbl_table_model);

        tbl_table_model_candidates = new DefaultTableModel();
        tbl_table_model_candidates.setColumnIdentifiers(new Object[]{"ID", "NAME", "EMAIL", "ADDRESS", "EXPACTAION", "EXPERIENCE", "GENDER"});
        tbl_admin_candidate_management1.setModel(tbl_table_model_candidates);
        SetCandidatesToTable();

    }

    private void SetCandidatesToTable() {
        ArrayList<Candidate> candidates = CompanyDB.GetCandidates();
        tbl_table_model_candidates.setRowCount(0);
        for (Candidate candidate : candidates) {
            tbl_table_model_candidates.addRow(new Object[]{candidate.id, candidate.name_surname, candidate.email, candidate.address, candidate.expectations, candidate.experience, candidate.gender});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_admin_emplooyes_management = new javax.swing.JTable();
        btn_admin_emplooyes_management_delete = new javax.swing.JButton();
        btn_admin_emplooyes_management_update = new javax.swing.JButton();
        btn_admin_emplooyes_management_add = new javax.swing.JButton();
        btn_admin_emplooyes_management_refresh = new javax.swing.JButton();
        btn_admin_emplooyes_management_search = new javax.swing.JButton();
        txt_admin_emplooyes_management_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_emplooye_email = new javax.swing.JTextField();
        txt_emplooye_id = new javax.swing.JTextField();
        txt_emplooye_name_surname = new javax.swing.JTextField();
        txt_emplooye_password = new javax.swing.JTextField();
        txt_emplooye_address = new javax.swing.JTextField();
        cmbx_emplooye_gender = new javax.swing.JComboBox<>();
        cmx_emplooye_position = new javax.swing.JComboBox<>();
        txt_emplooye_salary = new javax.swing.JTextField();
        btn_admin_emplooyes_management_clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_candidate_name_surname = new javax.swing.JTextField();
        txt_candidate_email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_candidate_password = new javax.swing.JTextField();
        txt_candidate_address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbx_candidate_gender = new javax.swing.JComboBox<>();
        cmbx_candidate_position = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_candidate_salary = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_admin_candidate_management1 = new javax.swing.JTable();
        txt_admin_candidate_management_search1 = new javax.swing.JTextField();
        btn_admin_candidate_management_search1 = new javax.swing.JButton();
        btn_admin_candidate_management_reject = new javax.swing.JButton();
        btn_admin_candidate_management_approve = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_back_to_login = new javax.swing.JMenuItem();
        mi_back_to_panel = new javax.swing.JMenuItem();
        mi_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(139, 20, 70));

        tbl_admin_emplooyes_management.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_admin_emplooyes_management.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_admin_emplooyes_managementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_admin_emplooyes_management);

        btn_admin_emplooyes_management_delete.setBackground(new java.awt.Color(239, 20, 60));
        btn_admin_emplooyes_management_delete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_emplooyes_management_delete.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_emplooyes_management_delete.setText("Delete");
        btn_admin_emplooyes_management_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_emplooyes_management_deleteActionPerformed(evt);
            }
        });

        btn_admin_emplooyes_management_update.setBackground(new java.awt.Color(238, 232, 170));
        btn_admin_emplooyes_management_update.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_emplooyes_management_update.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_emplooyes_management_update.setText("Update");
        btn_admin_emplooyes_management_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_emplooyes_management_updateActionPerformed(evt);
            }
        });

        btn_admin_emplooyes_management_add.setBackground(new java.awt.Color(30, 144, 255));
        btn_admin_emplooyes_management_add.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_emplooyes_management_add.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_emplooyes_management_add.setText("Add");
        btn_admin_emplooyes_management_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_emplooyes_management_addActionPerformed(evt);
            }
        });

        btn_admin_emplooyes_management_refresh.setBackground(new java.awt.Color(224, 255, 255));
        btn_admin_emplooyes_management_refresh.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_emplooyes_management_refresh.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_emplooyes_management_refresh.setText("Refresh");
        btn_admin_emplooyes_management_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_emplooyes_management_refreshActionPerformed(evt);
            }
        });

        btn_admin_emplooyes_management_search.setBackground(new java.awt.Color(230, 230, 250));
        btn_admin_emplooyes_management_search.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_emplooyes_management_search.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_emplooyes_management_search.setText("Search");
        btn_admin_emplooyes_management_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_emplooyes_management_searchActionPerformed(evt);
            }
        });

        txt_admin_emplooyes_management_search.setBackground(new java.awt.Color(176, 196, 222));
        txt_admin_emplooyes_management_search.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txt_admin_emplooyes_management_search.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Name Surname");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Id");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("Position");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("Salary");

        txt_emplooye_email.setBackground(new java.awt.Color(204, 204, 255));

        txt_emplooye_id.setBackground(new java.awt.Color(204, 204, 255));

        txt_emplooye_name_surname.setBackground(new java.awt.Color(204, 204, 255));

        txt_emplooye_password.setBackground(new java.awt.Color(204, 204, 255));

        txt_emplooye_address.setBackground(new java.awt.Color(204, 204, 255));

        cmbx_emplooye_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        cmx_emplooye_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Ceo", "Designer", "Database Manager", "Admin" }));

        txt_emplooye_salary.setBackground(new java.awt.Color(204, 204, 255));

        btn_admin_emplooyes_management_clear.setBackground(new java.awt.Color(255, 255, 255));
        btn_admin_emplooyes_management_clear.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_emplooyes_management_clear.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_emplooyes_management_clear.setText("Clear");
        btn_admin_emplooyes_management_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_emplooyes_management_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txt_admin_emplooyes_management_search, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_admin_emplooyes_management_search, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btn_admin_emplooyes_management_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_admin_emplooyes_management_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_emplooye_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_emplooye_email, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_emplooye_id, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_emplooye_password, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_emplooye_address, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmx_emplooye_position, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbx_emplooye_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_emplooye_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_admin_emplooyes_management_add, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_admin_emplooyes_management_update, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_admin_emplooyes_management_clear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_admin_emplooyes_management_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_admin_emplooyes_management_search, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_admin_emplooyes_management_add, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_admin_emplooyes_management_update, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_admin_emplooyes_management_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_emplooye_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_emplooye_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_emplooye_email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_emplooye_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_emplooye_address, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbx_emplooye_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmx_emplooye_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txt_emplooye_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_admin_emplooyes_management_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_admin_emplooyes_management_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))))
        );

        jTabbedPane1.addTab("Staff", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setText("Name Surname");

        txt_candidate_name_surname.setBackground(new java.awt.Color(204, 204, 255));

        txt_candidate_email.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setText("Password");

        txt_candidate_password.setBackground(new java.awt.Color(204, 204, 255));

        txt_candidate_address.setBackground(new java.awt.Color(204, 204, 255));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel12.setText("Address");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setText("Gender");

        cmbx_candidate_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        cmbx_candidate_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Ceo", "Designer", "Database Manager", "Admin" }));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel14.setText("Position");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel15.setText("Salary");

        txt_candidate_salary.setBackground(new java.awt.Color(204, 204, 255));

        tbl_admin_candidate_management1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_admin_candidate_management1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_admin_candidate_management1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_admin_candidate_management1);

        txt_admin_candidate_management_search1.setBackground(new java.awt.Color(176, 196, 222));
        txt_admin_candidate_management_search1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txt_admin_candidate_management_search1.setForeground(new java.awt.Color(0, 0, 0));

        btn_admin_candidate_management_search1.setBackground(new java.awt.Color(230, 230, 250));
        btn_admin_candidate_management_search1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_candidate_management_search1.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_candidate_management_search1.setText("Search");
        btn_admin_candidate_management_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_candidate_management_search1ActionPerformed(evt);
            }
        });

        btn_admin_candidate_management_reject.setBackground(new java.awt.Color(255, 102, 102));
        btn_admin_candidate_management_reject.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_candidate_management_reject.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_candidate_management_reject.setText("Reject");
        btn_admin_candidate_management_reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_candidate_management_rejectActionPerformed(evt);
            }
        });

        btn_admin_candidate_management_approve.setBackground(new java.awt.Color(238, 232, 170));
        btn_admin_candidate_management_approve.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_candidate_management_approve.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_candidate_management_approve.setText("Approve");
        btn_admin_candidate_management_approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_candidate_management_approveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_admin_candidate_management_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_admin_candidate_management_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_candidate_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_candidate_email, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_candidate_password, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_candidate_address, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbx_candidate_position, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbx_candidate_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_candidate_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_admin_candidate_management_reject, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(958, Short.MAX_VALUE)
                    .addComponent(btn_admin_candidate_management_approve, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(100, 100, 100)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_admin_candidate_management_search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_admin_candidate_management_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_candidate_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_candidate_email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_candidate_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_candidate_address, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbx_candidate_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbx_candidate_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(txt_candidate_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btn_admin_candidate_management_reject, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(680, Short.MAX_VALUE)
                    .addComponent(btn_admin_candidate_management_approve, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)))
        );

        jTabbedPane1.addTab("Application", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 830));

        jMenu1.setText("Menu");

        mi_back_to_login.setText("Back to login");
        mi_back_to_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_back_to_loginActionPerformed(evt);
            }
        });
        jMenu1.add(mi_back_to_login);

        mi_back_to_panel.setText("Back to panel");
        mi_back_to_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_back_to_panelActionPerformed(evt);
            }
        });
        jMenu1.add(mi_back_to_panel);

        mi_exit.setText("Exit");
        mi_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_exitActionPerformed(evt);
            }
        });
        jMenu1.add(mi_exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_admin_emplooyes_management_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_emplooyes_management_addActionPerformed

        Staff np1 = new Staff();

        np1.name_surname = txt_emplooye_name_surname.getText();
        np1.email = txt_emplooye_email.getText();
        np1.password = txt_emplooye_password.getText();
        np1.address = txt_emplooye_address.getText();
        np1.gender = cmbx_emplooye_gender.getSelectedItem().toString();
        np1.position = cmx_emplooye_position.getSelectedItem().toString();
        double salary = Double.parseDouble(txt_emplooye_salary.getText());
        np1.salary = salary;

        if (CompanyDB.AddStaff(np1)) {
            JOptionPane.showMessageDialog(rootPane, "Added");
            if (tbl_admin_candidate_management1.getSelectedRow() < 0) {
                return;

            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Not Added");
        }


    }//GEN-LAST:event_btn_admin_emplooyes_management_addActionPerformed

    private void btn_admin_emplooyes_management_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_emplooyes_management_searchActionPerformed
        String search = txt_admin_emplooyes_management_search.getText();
        tbl_table_model.setRowCount(0);
        ArrayList<Staff> slist = CompanyDB.SearchByNameOrEmail(search);
        for (Staff np1 : slist) {
            tbl_table_model.addRow(new Object[]{np1.id, np1.name_surname, np1.email, np1.password, np1.address, np1.gender, np1.position, np1.salary});

        }

    }//GEN-LAST:event_btn_admin_emplooyes_management_searchActionPerformed

    private void btn_admin_emplooyes_management_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_emplooyes_management_refreshActionPerformed
        try {
            if (CompanyDB.transferData1()) {

                JOptionPane.showMessageDialog(rootPane, "Refreshed!");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Could not be refreshed");

            }

        } catch (SQLException ex) {
            Logger.getLogger(Admin_Emplooyes_Management.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_admin_emplooyes_management_refreshActionPerformed

    private void btn_admin_candidate_management_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_candidate_management_search1ActionPerformed

        String search = txt_admin_candidate_management_search1.getText();
        tbl_table_model_candidates.setRowCount(0);
        ArrayList<Candidate> clist = CompanyDB.SearchCandidate(search);
        for (Candidate candidate : clist) {
            tbl_table_model_candidates.addRow(new Object[]{candidate.id, candidate.name_surname, candidate.email, candidate.address, candidate.expectations, candidate.experience, candidate.gender});

        }


    }//GEN-LAST:event_btn_admin_candidate_management_search1ActionPerformed

    private void tbl_admin_candidate_management1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_admin_candidate_management1MouseClicked
        if (tbl_admin_candidate_management1.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tbl_table_model_candidates.getValueAt(tbl_admin_candidate_management1.getSelectedRow(), 0);

        Candidate cndt = CompanyDB.SearchPersonById(id);
        if (cndt != null) {
            txt_candidate_name_surname.setText(cndt.name_surname);
            txt_candidate_email.setText(cndt.email);
            txt_candidate_address.setText(cndt.address);
            txt_candidate_email.setEditable(false);
            txt_candidate_name_surname.setEditable(false);

        }


    }//GEN-LAST:event_tbl_admin_candidate_management1MouseClicked

    private void btn_admin_candidate_management_approveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_candidate_management_approveActionPerformed

        Staff np1 = new Staff();

        np1.name_surname = txt_candidate_name_surname.getText();
        np1.email = txt_candidate_email.getText();
        np1.password = txt_candidate_password.getText();
        np1.address = txt_candidate_address.getText();
        np1.gender = cmbx_candidate_gender.getSelectedItem().toString();
        np1.position = cmbx_candidate_position.getSelectedItem().toString();
        double salary = Double.parseDouble(txt_candidate_salary.getText());
        np1.salary = salary;

        if (CompanyDB.AddStaff(np1)) {
            JOptionPane.showMessageDialog(rootPane, "Approved");
            if (tbl_admin_candidate_management1.getSelectedRow() < 0) {
                return;

            }
            int id_candidates = Integer.parseInt(tbl_table_model_candidates.getValueAt(tbl_admin_candidate_management1.getSelectedRow(), 0).toString());
            String name_surname = txt_candidate_name_surname.getText();
            String email = txt_candidate_email.getText();
            CompanyDB.DeleteCandidate(id_candidates, name_surname, email);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Not Approved");
        }


    }//GEN-LAST:event_btn_admin_candidate_management_approveActionPerformed

    private void btn_admin_candidate_management_rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_candidate_management_rejectActionPerformed

        if (tbl_admin_candidate_management1.getSelectedRow() < 0) {
            return;

        }
        int id_candidates = Integer.parseInt(tbl_table_model_candidates.getValueAt(tbl_admin_candidate_management1.getSelectedRow(), 0).toString());
        String name_surname = txt_candidate_name_surname.getText();
        String email = txt_candidate_email.getText();
        CompanyDB.DeleteCandidate(id_candidates, name_surname, email);


    }//GEN-LAST:event_btn_admin_candidate_management_rejectActionPerformed

    private void tbl_admin_emplooyes_managementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_admin_emplooyes_managementMouseClicked

        if (tbl_admin_emplooyes_management.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tbl_table_model.getValueAt(tbl_admin_emplooyes_management.getSelectedRow(), 0);

        Staff stf = CompanyDB.SearchStaffById(id);
        if (stf != null) {
            txt_emplooye_id.setText(stf.id + "");
            txt_emplooye_name_surname.setText(stf.name_surname);
            txt_emplooye_email.setText(stf.email);
            txt_emplooye_password.setText(stf.password);
            txt_emplooye_address.setText(stf.address);
            txt_emplooye_salary.setText(stf.salary + "");
            cmbx_emplooye_gender.setSelectedItem(stf.gender);
            cmx_emplooye_position.setSelectedItem(stf.position);

            txt_emplooye_email.setEditable(false);
            txt_emplooye_name_surname.setEditable(false);

        }

    }//GEN-LAST:event_tbl_admin_emplooyes_managementMouseClicked

    private void btn_admin_emplooyes_management_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_emplooyes_management_updateActionPerformed

        Staff np1 = new Staff();

        np1.id = Integer.parseInt(txt_emplooye_id.getText());
        np1.name_surname = txt_emplooye_name_surname.getText();
        np1.email = txt_emplooye_email.getText();
        np1.password = txt_emplooye_password.getText();
        np1.address = txt_emplooye_address.getText();
        np1.gender = (String) cmbx_emplooye_gender.getSelectedItem();
        np1.position = cmx_emplooye_position.getSelectedItem().toString();
        np1.salary = Double.parseDouble(txt_emplooye_salary.getText());
        if (CompanyDB.UpdateStaff(np1)) {
            JOptionPane.showMessageDialog(rootPane, "Updated");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Not Updated");
        }


    }//GEN-LAST:event_btn_admin_emplooyes_management_updateActionPerformed

    private void btn_admin_emplooyes_management_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_emplooyes_management_deleteActionPerformed

        if (tbl_admin_emplooyes_management.getSelectedRow() < 0) {
            return;

        }
        int id_staff = Integer.parseInt(tbl_table_model.getValueAt(tbl_admin_emplooyes_management.getSelectedRow(), 0).toString());
        String name_surname = txt_emplooye_name_surname.getText();
        String email = txt_emplooye_email.getText();

        if (CompanyDB.DeleteStaff(id_staff, name_surname, email)) {
            JOptionPane.showMessageDialog(rootPane, "Deleted");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Could not be deleted");

        }


    }//GEN-LAST:event_btn_admin_emplooyes_management_deleteActionPerformed

    private void btn_admin_emplooyes_management_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_emplooyes_management_clearActionPerformed

        txt_emplooye_id.setText("");
        txt_emplooye_name_surname.setText("");
        txt_emplooye_email.setText("");
        txt_emplooye_password.setText("");
        txt_emplooye_address.setText("");
        txt_emplooye_salary.setText("");
        cmbx_emplooye_gender.setSelectedItem(0);
        cmx_emplooye_position.setSelectedItem(0);

        txt_emplooye_email.setEditable(true);
        txt_emplooye_name_surname.setEditable(true);
        

    }//GEN-LAST:event_btn_admin_emplooyes_management_clearActionPerformed

    private void mi_back_to_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_back_to_panelActionPerformed
        AdminPanel admpnl = new AdminPanel();
        admpnl.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_mi_back_to_panelActionPerformed

    private void mi_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_exitActionPerformed
        System.exit(0);
        

    }//GEN-LAST:event_mi_exitActionPerformed

    private void mi_back_to_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_back_to_loginActionPerformed
        Login lgn = new Login();
        lgn.setVisible(true);
        this.dispose();


        
    }//GEN-LAST:event_mi_back_to_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Emplooyes_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Emplooyes_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Emplooyes_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Emplooyes_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Emplooyes_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin_candidate_management_approve;
    private javax.swing.JButton btn_admin_candidate_management_reject;
    private javax.swing.JButton btn_admin_candidate_management_search1;
    private javax.swing.JButton btn_admin_emplooyes_management_add;
    private javax.swing.JButton btn_admin_emplooyes_management_clear;
    private javax.swing.JButton btn_admin_emplooyes_management_delete;
    private javax.swing.JButton btn_admin_emplooyes_management_refresh;
    private javax.swing.JButton btn_admin_emplooyes_management_search;
    private javax.swing.JButton btn_admin_emplooyes_management_update;
    private javax.swing.JComboBox<String> cmbx_candidate_gender;
    private javax.swing.JComboBox<String> cmbx_candidate_position;
    private javax.swing.JComboBox<String> cmbx_emplooye_gender;
    private javax.swing.JComboBox<String> cmx_emplooye_position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mi_back_to_login;
    private javax.swing.JMenuItem mi_back_to_panel;
    private javax.swing.JMenuItem mi_exit;
    private javax.swing.JTable tbl_admin_candidate_management1;
    private javax.swing.JTable tbl_admin_emplooyes_management;
    private javax.swing.JTextField txt_admin_candidate_management_search1;
    private javax.swing.JTextField txt_admin_emplooyes_management_search;
    private javax.swing.JTextField txt_candidate_address;
    private javax.swing.JTextField txt_candidate_email;
    private javax.swing.JTextField txt_candidate_name_surname;
    private javax.swing.JTextField txt_candidate_password;
    private javax.swing.JTextField txt_candidate_salary;
    private javax.swing.JTextField txt_emplooye_address;
    private javax.swing.JTextField txt_emplooye_email;
    private javax.swing.JTextField txt_emplooye_id;
    private javax.swing.JTextField txt_emplooye_name_surname;
    private javax.swing.JTextField txt_emplooye_password;
    private javax.swing.JTextField txt_emplooye_salary;
    // End of variables declaration//GEN-END:variables
}
