/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2projelogintasarim;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    DefaultTableModel tbl_model;
    
    public AdminPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_general_info = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnl_personel_info = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnl_emplooyes_management = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_admin_panel_selected_name = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_admin_panel = new javax.swing.JTable();
        lbl_admin_panel_general_info = new javax.swing.JLabel();
        txt_admin_emplooyes_search = new javax.swing.JTextField();
        btn_admin_emplooyes_search = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_back_to_login = new javax.swing.JMenuItem();
        mi_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 164, 96));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Panel");

        pnl_general_info.setBackground(new java.awt.Color(244, 164, 96));
        pnl_general_info.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnl_general_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_general_infoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_general_infoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_general_infoMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("General Info");

        javax.swing.GroupLayout pnl_general_infoLayout = new javax.swing.GroupLayout(pnl_general_info);
        pnl_general_info.setLayout(pnl_general_infoLayout);
        pnl_general_infoLayout.setHorizontalGroup(
            pnl_general_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_general_infoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_general_infoLayout.setVerticalGroup(
            pnl_general_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_general_infoLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pnl_personel_info.setBackground(new java.awt.Color(244, 164, 96));
        pnl_personel_info.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnl_personel_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_personel_infoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_personel_infoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_personel_infoMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Personel Info");

        javax.swing.GroupLayout pnl_personel_infoLayout = new javax.swing.GroupLayout(pnl_personel_info);
        pnl_personel_info.setLayout(pnl_personel_infoLayout);
        pnl_personel_infoLayout.setHorizontalGroup(
            pnl_personel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personel_infoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnl_personel_infoLayout.setVerticalGroup(
            pnl_personel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personel_infoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnl_emplooyes_management.setBackground(new java.awt.Color(244, 164, 96));
        pnl_emplooyes_management.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnl_emplooyes_management.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_emplooyes_managementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_emplooyes_managementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_emplooyes_managementMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Emplooyes Management");

        javax.swing.GroupLayout pnl_emplooyes_managementLayout = new javax.swing.GroupLayout(pnl_emplooyes_management);
        pnl_emplooyes_management.setLayout(pnl_emplooyes_managementLayout);
        pnl_emplooyes_managementLayout.setHorizontalGroup(
            pnl_emplooyes_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_emplooyes_managementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_emplooyes_managementLayout.setVerticalGroup(
            pnl_emplooyes_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_emplooyes_managementLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_personel_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnl_general_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pnl_emplooyes_management, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(pnl_general_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnl_personel_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_emplooyes_management, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 660));

        jPanel2.setBackground(new java.awt.Color(255, 218, 185));

        lbl_admin_panel_selected_name.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_admin_panel_selected_name.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_admin_panel_selected_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(663, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_admin_panel_selected_name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 840, 80));

        jPanel3.setBackground(new java.awt.Color(192, 192, 192));

        tbl_admin_panel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_admin_panel);

        lbl_admin_panel_general_info.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_admin_panel_general_info.setForeground(new java.awt.Color(0, 0, 0));

        txt_admin_emplooyes_search.setBackground(new java.awt.Color(176, 196, 222));
        txt_admin_emplooyes_search.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txt_admin_emplooyes_search.setForeground(new java.awt.Color(0, 0, 0));

        btn_admin_emplooyes_search.setBackground(new java.awt.Color(230, 230, 250));
        btn_admin_emplooyes_search.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_admin_emplooyes_search.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin_emplooyes_search.setText("Search");
        btn_admin_emplooyes_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_emplooyes_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txt_admin_emplooyes_search, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_admin_emplooyes_search, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_admin_panel_general_info, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_admin_panel_general_info, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_admin_emplooyes_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_admin_emplooyes_search, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 840, 580));

        jMenu1.setText("Menu");

        mi_back_to_login.setText("Back to login");
        mi_back_to_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_back_to_loginActionPerformed(evt);
            }
        });
        jMenu1.add(mi_back_to_login);

        mi_exit.setText("Exit");
        mi_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_exitActionPerformed(evt);
            }
        });
        jMenu1.add(mi_exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_general_infoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_general_infoMouseEntered
        Color clr = new Color(200, 80, 59);
        pnl_general_info.setBackground(clr);
        

    }//GEN-LAST:event_pnl_general_infoMouseEntered

    private void pnl_general_infoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_general_infoMouseExited
        Color clr = new Color(244, 164, 96);
        pnl_general_info.setBackground(clr);
        

    }//GEN-LAST:event_pnl_general_infoMouseExited

    private void pnl_personel_infoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_personel_infoMouseEntered
        Color clr = new Color(200, 80, 59);
        pnl_personel_info.setBackground(clr);
        

    }//GEN-LAST:event_pnl_personel_infoMouseEntered

    private void pnl_personel_infoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_personel_infoMouseExited
        Color clr = new Color(244, 164, 96);
        pnl_personel_info.setBackground(clr);

    }//GEN-LAST:event_pnl_personel_infoMouseExited

    private void pnl_emplooyes_managementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_emplooyes_managementMouseEntered
        Color clr = new Color(200, 80, 59);
        pnl_emplooyes_management.setBackground(clr);
    }//GEN-LAST:event_pnl_emplooyes_managementMouseEntered

    private void pnl_emplooyes_managementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_emplooyes_managementMouseExited
        Color clr = new Color(244, 164, 96);
        pnl_emplooyes_management.setBackground(clr);
        

    }//GEN-LAST:event_pnl_emplooyes_managementMouseExited

    private void pnl_general_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_general_infoMouseClicked
        
        tbl_model = new DefaultTableModel();
        tbl_model.setColumnIdentifiers(new Object[]{"ID", "NAME", "EMAIL", "ADDRESS", "GENDER", "POSITION"});
        tbl_admin_panel.setModel(tbl_model);
        SetStaffToTable();
        

    }//GEN-LAST:event_pnl_general_infoMouseClicked

    private void pnl_emplooyes_managementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_emplooyes_managementMouseClicked
        
        Admin_Emplooyes_Management emp = new Admin_Emplooyes_Management();
        emp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_pnl_emplooyes_managementMouseClicked

    private void pnl_personel_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_personel_infoMouseClicked
        
        tbl_model = new DefaultTableModel();
        tbl_model.setColumnIdentifiers(new Object[]{"ID", "NAME", "EMAIL", "ADDRESS", "GENDER", "POSITION", "SALARY"});
        tbl_admin_panel.setModel(tbl_model);
        SetStaffToTable();
        

    }//GEN-LAST:event_pnl_personel_infoMouseClicked

    private void mi_back_to_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_back_to_loginActionPerformed

        // TODO add your handling code here:
        logintasarim lgn = new logintasarim();
        lgn.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_mi_back_to_loginActionPerformed

    private void mi_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_exitActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mi_exitActionPerformed

    private void btn_admin_emplooyes_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_emplooyes_searchActionPerformed
        String search = txt_admin_emplooyes_search.getText();
        tbl_model.setRowCount(0);
        ArrayList<Staff> slist = CompanyDB.SearchByNameOrEmail(search);
        for (Staff np1 : slist) {
            tbl_model.addRow(new Object[]{np1.id, np1.name_surname, np1.email, np1.address, np1.gender, np1.position, np1.salary});

        }
    }//GEN-LAST:event_btn_admin_emplooyes_searchActionPerformed
    
    private void SetStaffToTable() {
        ArrayList<Staff> stfs = CompanyDB.GetStaff();
        tbl_model.setRowCount(0);
        for (Staff staff : stfs) {
            tbl_model.addRow(new Object[]{staff.id, staff.name_surname, staff.email, staff.address, staff.gender, staff.position, staff.salary});
            
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin_emplooyes_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_admin_panel_general_info;
    private javax.swing.JLabel lbl_admin_panel_selected_name;
    private javax.swing.JMenuItem mi_back_to_login;
    private javax.swing.JMenuItem mi_exit;
    private javax.swing.JPanel pnl_emplooyes_management;
    private javax.swing.JPanel pnl_general_info;
    private javax.swing.JPanel pnl_personel_info;
    private javax.swing.JTable tbl_admin_panel;
    private javax.swing.JTextField txt_admin_emplooyes_search;
    // End of variables declaration//GEN-END:variables
}
