/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2projelogintasarim;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author pc
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_register = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_register_min = new javax.swing.JLabel();
        lbl_register_close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ptxt_register_password = new javax.swing.JPasswordField();
        btn_register_clear = new javax.swing.JButton();
        btn_register_cancel = new javax.swing.JButton();
        btn_register_register = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_register_name_surname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_register_email = new javax.swing.JTextField();
        ptxt_register_rtpassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        txt_register_address = new javax.swing.JTextField();
        lbl_register_login = new javax.swing.JLabel();
        cmbx_register_position = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbx_register_gender = new javax.swing.JComboBox<>();
        chbx_register_show_pass = new javax.swing.JCheckBox();
        chbx_register_show_rtpass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 122));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register Form");

        lbl_register_min.setBackground(new java.awt.Color(102, 102, 255));
        lbl_register_min.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_register_min.setForeground(new java.awt.Color(0, 0, 0));
        lbl_register_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register_min.setText("-");
        lbl_register_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_register_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_register_minMouseClicked(evt);
            }
        });

        lbl_register_close.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_register_close.setForeground(new java.awt.Color(0, 0, 0));
        lbl_register_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register_close.setText("X");
        lbl_register_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_register_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_register_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(lbl_register_min, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_register_close, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_register_min, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_register_close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(57, 89, 99));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Password");

        ptxt_register_password.setBackground(new java.awt.Color(108, 122, 150));
        ptxt_register_password.setForeground(new java.awt.Color(228, 241, 249));
        ptxt_register_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptxt_register_passwordActionPerformed(evt);
            }
        });

        btn_register_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_register_clear.setForeground(new java.awt.Color(0, 0, 0));
        btn_register_clear.setText("Clear");
        btn_register_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register_clearActionPerformed(evt);
            }
        });

        btn_register_cancel.setBackground(new java.awt.Color(192, 57, 49));
        btn_register_cancel.setForeground(new java.awt.Color(0, 0, 0));
        btn_register_cancel.setText("Cancel");
        btn_register_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register_cancelActionPerformed(evt);
            }
        });

        btn_register_register.setBackground(new java.awt.Color(34, 167, 244));
        btn_register_register.setForeground(new java.awt.Color(0, 0, 0));
        btn_register_register.setText("Register");
        btn_register_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register_registerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Name Surname");

        txt_register_name_surname.setBackground(new java.awt.Color(108, 122, 150));
        txt_register_name_surname.setForeground(new java.awt.Color(228, 241, 249));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("Email");

        txt_register_email.setBackground(new java.awt.Color(108, 122, 150));
        txt_register_email.setForeground(new java.awt.Color(228, 241, 249));

        ptxt_register_rtpassword.setBackground(new java.awt.Color(108, 122, 150));
        ptxt_register_rtpassword.setForeground(new java.awt.Color(228, 241, 249));
        ptxt_register_rtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptxt_register_rtpasswordActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setText("Retype Pass");

        Gender.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Gender.setText("Gender");

        txt_register_address.setBackground(new java.awt.Color(108, 122, 150));
        txt_register_address.setForeground(new java.awt.Color(228, 241, 249));

        lbl_register_login.setText("Click here to login ");
        lbl_register_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_register_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_register_loginMouseClicked(evt);
            }
        });

        cmbx_register_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Designer", "Database Manager", "Admin", "Ceo", " " }));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setText("Address");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel12.setText("Position");

        cmbx_register_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        chbx_register_show_pass.setText("Show");
        chbx_register_show_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbx_register_show_passMouseClicked(evt);
            }
        });

        chbx_register_show_rtpass.setText("Show");
        chbx_register_show_rtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbx_register_show_rtpassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ptxt_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbx_register_show_pass))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ptxt_register_rtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chbx_register_show_rtpass))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btn_register_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_register_login, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btn_register_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(btn_register_register, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbx_register_position, 0, 0, Short.MAX_VALUE)
                                            .addComponent(cmbx_register_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_register_address, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_register_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_register_email, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(391, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_register_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_register_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptxt_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbx_register_show_pass))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptxt_register_rtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbx_register_show_rtpass))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_register_address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cmbx_register_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(cmbx_register_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_register_register, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_register_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_register_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lbl_register_login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(453, 453, 453)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGap(144, 144, 144)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_register_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_register_minMouseClicked
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_lbl_register_minMouseClicked

    private void lbl_register_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_register_closeMouseClicked
        System.exit(0);

    }//GEN-LAST:event_lbl_register_closeMouseClicked

    private void btn_register_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register_cancelActionPerformed
        Login lgn = new Login();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_btn_register_cancelActionPerformed

    private void ptxt_register_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptxt_register_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptxt_register_passwordActionPerformed

    private void ptxt_register_rtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptxt_register_rtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptxt_register_rtpasswordActionPerformed

    private void lbl_register_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_register_loginMouseClicked

        Login lgn = new Login();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_lbl_register_loginMouseClicked

    private void btn_register_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register_clearActionPerformed
        txt_register_name_surname.setText("");
        txt_register_email.setText("");
        txt_register_address.setText("");
        ptxt_register_password.setText("");
        ptxt_register_rtpassword.setText("");
        cmbx_register_position.setSelectedIndex(0);
        cmbx_register_gender.setSelectedIndex(0);

    }//GEN-LAST:event_btn_register_clearActionPerformed


    private void btn_register_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register_registerActionPerformed

        Person np1 = new Person();
        String pass = String.valueOf(ptxt_register_password.getPassword());
        String re_pass = String.valueOf(ptxt_register_rtpassword.getPassword());

        /*Pattern pattern_email = Pattern.compile("^([a-z]+\\w*){3,}@{1}((gmail)|(hotmail)){1}(.com){1}$");
        Matcher matcher_email = pattern_email.matcher(txt_register_email.getText());
        Pattern pattern_name_surname = Pattern.compile("((([A-Z]{1}+[a-zA-Z]{2,})+\\s)+([A-Z]{1}+[a-zA-Z]{2,})$)");
        Matcher matcher_name_surname = pattern_name_surname.matcher(txt_register_name_surname.getText());
        Pattern pattern_password = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-+∫]).{8,}$");
        Matcher matcher_password = pattern_password.matcher(ptxt_register_password.getText());

         */
        String[] regexPattern = {"((([A-Z]{1}+[a-zA-Z]{2,})+\\s)+([A-Z]{1}+[a-zA-Z]{2,})$)",
            "^([a-z]+\\w*){3,}@{1}((gmail)|(hotmail)){1}(.com){1}$",
            "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*\\\\-\\\\=+∫,#;(Ω≤≥]).{8,}$"};
        String[] textToPattern = {txt_register_name_surname.getText(),
            txt_register_email.getText(),
            ptxt_register_password.getText()};

        boolean isValid = true;
        if (CompanyDB.isEmailExists(txt_register_email.getText())) {
            isValid=false;
            JOptionPane.showMessageDialog(this, "This email is already in use");
        }
        
        for (int i = 0; i < regexPattern.length; i++) {
            Pattern pattern = Pattern.compile(regexPattern[i]);
            Matcher matcher = pattern.matcher(textToPattern[i]);

            if (!matcher.find()) {
                isValid = false;
                switch (i) {
                    case 0:
                        
                        JOptionPane.showMessageDialog(this, "Uygun bir name surname giriniz! \n"
                                + "\" A--- A--- formatinda en az 3 harf olacak sekilde giriniz\"");

                        break;
                    case 1:
                        JOptionPane.showMessageDialog(this, "Uygun bir email giriniz!\n"
                                + "----@gmail|hotmail.com formatında giriniz");

                        break;
                    case 2:

                        if (pass.compareTo(re_pass) != 0) {
                            JOptionPane.showMessageDialog(this, "Şifreler uyuşmuyor");

                        }

                        JOptionPane.showMessageDialog(this, "Uygun bir password giriniz!\n"
                                + "Bir büyük harf, sayı ve sembol kullanarak en az 8 karakter olacak şekilde giriniz");
                        break;

                }

            }

        }
        if (isValid) {
            np1.name_surname = txt_register_name_surname.getText();
            np1.email = txt_register_email.getText();
            np1.password = ptxt_register_password.getText();
            np1.address = txt_register_address.getText();
            np1.gender = cmbx_register_gender.getSelectedItem().toString();
            np1.position = cmbx_register_position.getSelectedItem().toString();

            if (CompanyDB.AddPerson(np1)) {
                JOptionPane.showMessageDialog(this, "Added");

            } else {
                JOptionPane.showMessageDialog(this, "Not Added");
            }

        }

        /*
        np1.name_surname = txt_register_name_surname.getText();
                np1.email = txt_register_email.getText();
                np1.password = ptxt_register_password.getText();
                np1.address = txt_register_address.getText();
                np1.gender = cmbx_register_gender.getSelectedItem().toString();
                np1.position = cmbx_register_position.getSelectedItem().toString();

                if (CompanyDB.AddPerson(np1)) {
                    JOptionPane.showMessageDialog(this, "Added");

                } else {
                    JOptionPane.showMessageDialog(this, "Not Added");
                }
         */ //((([A-Z]{1}+[a-zA-Z]{2,})+\s)+([A-Z]{1}+[a-zA-Z]{2,})$)
        //^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-+∫]).{8,}$
        //^([a-z]+\\w*){3,}@{1}((gmail)|(hotmail)){1}(.com){1}$
        //Asdfgh12, 
        //f(!pass.equals(re_pass)){
        //JOptionPane.showMessageDialog(this, "Sifreler uyusmuyor.");

    }//GEN-LAST:event_btn_register_registerActionPerformed

    private void chbx_register_show_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbx_register_show_passMouseClicked

        if (chbx_register_show_pass.isSelected()) {
            ptxt_register_password.setEchoChar((char) 0);

        } else {
            ptxt_register_password.setEchoChar('*');
        }
    }//GEN-LAST:event_chbx_register_show_passMouseClicked

    private void chbx_register_show_rtpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbx_register_show_rtpassMouseClicked
        if (chbx_register_show_rtpass.isSelected()) {
            ptxt_register_rtpassword.setEchoChar((char) 0);

        } else {
            ptxt_register_rtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chbx_register_show_rtpassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JButton btn_register_cancel;
    private javax.swing.JButton btn_register_clear;
    private javax.swing.JButton btn_register_register;
    private javax.swing.ButtonGroup btng_register;
    private javax.swing.JCheckBox chbx_register_show_pass;
    private javax.swing.JCheckBox chbx_register_show_rtpass;
    private javax.swing.JComboBox<String> cmbx_register_gender;
    private javax.swing.JComboBox<String> cmbx_register_position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_register_close;
    private javax.swing.JLabel lbl_register_login;
    private javax.swing.JLabel lbl_register_min;
    private javax.swing.JPasswordField ptxt_register_password;
    private javax.swing.JPasswordField ptxt_register_rtpassword;
    private javax.swing.JTextField txt_register_address;
    private javax.swing.JTextField txt_register_email;
    private javax.swing.JTextField txt_register_name_surname;
    // End of variables declaration//GEN-END:variables

}
