/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2projelogintasarim;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class StaffPanel_personel_info extends javax.swing.JFrame {

    /**
     * Creates new form StaffPanel_edit
     */
    DefaultTableModel tbl_table_staffE_model;

    public StaffPanel_personel_info() {
        initComponents();
        tbl_table_staffE_model = new DefaultTableModel();
        tbl_table_staffE_model.setColumnIdentifiers(new Object[]{"ID", "NAME", "EMAIL", "PASSWORD", "ADDRESS", "GENDER", "POSITION", "SALARY"});
        tbl_staffPanel_personel_info.setModel(tbl_table_staffE_model);
        txt_staffPanel_personel_info_address.setEditable(false);
        txt_staffPanel_personel_info_id.setEditable(false);
        txt_staffPanel_personel_info_name_surname.setEditable(false);
        cmbx_staffPanel_gender.setEditable(false);
        txt_staffPanel_personel_info_salary.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_staffPanel_personel_info = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_staffPanel_personel_info_name_surname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_staffPanel_personel_info_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_staffPanel_personel_info_password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_staffPanel_personel_info_address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbx_staffPanel_gender = new javax.swing.JComboBox<>();
        btn_staffPanel_personel_info_verify = new javax.swing.JButton();
        btn_staffPanel_personel_info_clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_staffPanel_personel_info_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_staffPanel_personel_info_salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbx_staffPanel_personel_info_position = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_back_to_panel = new javax.swing.JMenuItem();
        mi_exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        tbl_staffPanel_personel_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_staffPanel_personel_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_staffPanel_personel_infoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_staffPanel_personel_info);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name surname");

        txt_staffPanel_personel_info_name_surname.setBackground(new java.awt.Color(255, 204, 204));
        txt_staffPanel_personel_info_name_surname.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txt_staffPanel_personel_info_name_surname.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Email");

        txt_staffPanel_personel_info_email.setBackground(new java.awt.Color(255, 204, 204));
        txt_staffPanel_personel_info_email.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txt_staffPanel_personel_info_email.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");

        txt_staffPanel_personel_info_password.setBackground(new java.awt.Color(255, 204, 204));
        txt_staffPanel_personel_info_password.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txt_staffPanel_personel_info_password.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Address");

        txt_staffPanel_personel_info_address.setBackground(new java.awt.Color(255, 204, 204));
        txt_staffPanel_personel_info_address.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txt_staffPanel_personel_info_address.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Gender");

        cmbx_staffPanel_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        btn_staffPanel_personel_info_verify.setBackground(new java.awt.Color(255, 102, 102));
        btn_staffPanel_personel_info_verify.setForeground(new java.awt.Color(0, 0, 0));
        btn_staffPanel_personel_info_verify.setText("Verify");
        btn_staffPanel_personel_info_verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staffPanel_personel_info_verifyActionPerformed(evt);
            }
        });

        btn_staffPanel_personel_info_clear.setBackground(new java.awt.Color(204, 255, 255));
        btn_staffPanel_personel_info_clear.setForeground(new java.awt.Color(0, 0, 0));
        btn_staffPanel_personel_info_clear.setText("Clear");
        btn_staffPanel_personel_info_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staffPanel_personel_info_clearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID");

        txt_staffPanel_personel_info_id.setBackground(new java.awt.Color(255, 204, 204));
        txt_staffPanel_personel_info_id.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txt_staffPanel_personel_info_id.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Salary");

        txt_staffPanel_personel_info_salary.setBackground(new java.awt.Color(255, 204, 204));
        txt_staffPanel_personel_info_salary.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txt_staffPanel_personel_info_salary.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Position");

        cmbx_staffPanel_personel_info_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Designer", "Database Manager", "Admin", "Ceo", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_staffPanel_personel_info_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_staffPanel_personel_info_email, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_staffPanel_personel_info_password, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_staffPanel_personel_info_address, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_staffPanel_personel_info_id, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_staffPanel_personel_info_verify, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(btn_staffPanel_personel_info_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_staffPanel_personel_info_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbx_staffPanel_personel_info_position, 0, 1, Short.MAX_VALUE)
                            .addComponent(cmbx_staffPanel_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_staffPanel_personel_info_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_staffPanel_personel_info_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_staffPanel_personel_info_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_staffPanel_personel_info_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_staffPanel_personel_info_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbx_staffPanel_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbx_staffPanel_personel_info_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_staffPanel_personel_info_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_staffPanel_personel_info_verify, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_staffPanel_personel_info_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        jMenu1.setText("Menu");

        mi_back_to_panel.setText("Back to panel");
        mi_back_to_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_back_to_panelActionPerformed(evt);
            }
        });
        jMenu1.add(mi_back_to_panel);

        mi_exit.setText("Exit");
        mi_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_exitActionPerformed(evt);
            }
        });
        jMenu1.add(mi_exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Information");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_staffPanel_personel_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_staffPanel_personel_infoMouseClicked

        if (tbl_staffPanel_personel_info.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tbl_table_staffE_model.getValueAt(tbl_staffPanel_personel_info.getSelectedRow(), 0);

        Staff stff = CompanyDB.SearchStaffById(id);
        if (stff != null) {
            txt_staffPanel_personel_info_id.setText(stff.id + "");
            txt_staffPanel_personel_info_name_surname.setText(stff.name_surname);
            txt_staffPanel_personel_info_email.setText(stff.email);
            txt_staffPanel_personel_info_address.setText(stff.address);
            txt_staffPanel_personel_info_password.setText(stff.password);
            cmbx_staffPanel_gender.setSelectedItem(stff.gender);
            cmbx_staffPanel_personel_info_position.setSelectedItem(stff.position);
            txt_staffPanel_personel_info_salary.setText(stff.salary + "");

        }


    }//GEN-LAST:event_tbl_staffPanel_personel_infoMouseClicked

    private void btn_staffPanel_personel_info_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staffPanel_personel_info_clearActionPerformed

        txt_staffPanel_personel_info_id.setText("");
        txt_staffPanel_personel_info_email.setText("");
        txt_staffPanel_personel_info_address.setText("");
        txt_staffPanel_personel_info_password.setText("");
        txt_staffPanel_personel_info_name_surname.setText("");
        txt_staffPanel_personel_info_salary.setText("");
        cmbx_staffPanel_gender.setSelectedIndex(0);
        tbl_table_staffE_model.setRowCount(0);


    }//GEN-LAST:event_btn_staffPanel_personel_info_clearActionPerformed

    private void btn_staffPanel_personel_info_verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staffPanel_personel_info_verifyActionPerformed

        String email = txt_staffPanel_personel_info_email.getText();
        String password = txt_staffPanel_personel_info_password.getText();
        Staff staff = CompanyDB.StaffLogin(email, password);

        if (email.isEmpty() && password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your information in the boxes ");

        } else {
            if (staff != null) {
                JOptionPane.showMessageDialog(rootPane, "Verification successful");

                tbl_table_staffE_model.setRowCount(0);
                ArrayList<Staff> slist = CompanyDB.SearchByNameOrEmailStaffEdit(email);
                for (Staff stff : slist) {

                    tbl_table_staffE_model.addRow(new Object[]{stff.id, stff.name_surname, stff.email, stff.password, stff.address, stff.gender, stff.position, stff.salary});

                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Verification failed");
            }

        }


    }//GEN-LAST:event_btn_staffPanel_personel_info_verifyActionPerformed

    private void mi_back_to_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_back_to_panelActionPerformed
        StaffPanel stfpnl = new StaffPanel();
        stfpnl.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_mi_back_to_panelActionPerformed

    private void mi_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_exitActionPerformed

        System.exit(0);

    }//GEN-LAST:event_mi_exitActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

        JOptionPane.showMessageDialog(this, "To show your information, first enter and verify your email and password!"); 
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPanel_personel_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPanel_personel_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPanel_personel_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPanel_personel_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffPanel_personel_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_staffPanel_personel_info_clear;
    private javax.swing.JButton btn_staffPanel_personel_info_verify;
    private javax.swing.JComboBox<String> cmbx_staffPanel_gender;
    private javax.swing.JComboBox<String> cmbx_staffPanel_personel_info_position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mi_back_to_panel;
    private javax.swing.JMenuItem mi_exit;
    private javax.swing.JTable tbl_staffPanel_personel_info;
    private javax.swing.JTextField txt_staffPanel_personel_info_address;
    private javax.swing.JTextField txt_staffPanel_personel_info_email;
    private javax.swing.JTextField txt_staffPanel_personel_info_id;
    private javax.swing.JTextField txt_staffPanel_personel_info_name_surname;
    private javax.swing.JTextField txt_staffPanel_personel_info_password;
    private javax.swing.JTextField txt_staffPanel_personel_info_salary;
    // End of variables declaration//GEN-END:variables
}
